In [2]:
import pandas as pd

In [3]:
Diccionario_variables_alumnos= pd.read_excel('Data/Diccionario_variables_alumnos.xlsx')
Prestamos= pd.read_excel("Data/Prestamos_Data_Alumnos_v5.xlsx")

In [4]:
print("Diccionario_variables_alumnos:", Diccionario_variables_alumnos.shape)
print("Prestamos:", Prestamos.shape)

Diccionario_variables_alumnos: (19, 3)
Prestamos: (510704, 19)

In [5]:
Diccionario_variables_alumnos.head(5)

,Variables,Descripción,Valores
0,ID,Identificador único del préstamo.,Código identificador del cliente.
1,Edad,Edad del prestatario.,Valor numérico.
2,Ingresos,Ingreso anual del prestatario.,Valor numérico.
3,Monto_Inicial,Cantidad de dinero acordada.,Valor numérico.
4,Scoring_Crediticio,"La puntuación crediticia del prestatario, que ...",Valor numérico.

In [6]:
Prestamos.head(5)

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,O77MPJ,26,19153.0,6973,706,9.0,1,19.05,36.0,0.10,Grado Universitario,Jornada completa,Soltero,0.0,1.0,Automóvil,1.0,1,130.83
1,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,Escolar,Desempleado,Soltero,1.0,1.0,Vivienda,0.0,0,65.85
2,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,Máster,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,260.60
3,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,1.0,0,221.02
4,KG9CT9,34,56572.0,73978,763,86.0,1,13.91,60.0,0.55,Máster,Tiempo parcial,Soltero,0.0,0.0,Educación,0.0,0,800.00

# EDA (Análisis de Datos Exploratorio)

El análisis exploratorio (EDA) permite entender la estructura de los datos antes de modelar.
Se comprueban: valores nulos, tipos de datos, duplicados.

In [7]:
Prestamos.dtypes

ID                       object
Edad                      int64
Ingresos                float64
Monto_Inicial             int64
Scoring_Crediticio        int64
Meses_Empleo            float64
Num_Creditos              int64
Ratio_Interes           float64
Duracion                float64
Ratio_Deuda_Ingresos    float64
Estudios                 object
Tipo_Jornada_Laboral     object
Estado_Civil             object
Posesion_Hipoteca       float64
Personas_Cargo          float64
Proposito                object
Fiador                  float64
Impago                    int64
Prima                   float64
dtype: object

In [8]:
Prestamos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510704 entries, 0 to 510703
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    510704 non-null  object
 1   Edad                  510704 non-null  int64
 2   Ingresos              510703 non-null  float64
 3   Monto_Inicial         510704 non-null  int64
 4   Scoring_Crediticio    510704 non-null  int64
 5   Meses_Empleo          510702 non-null  float64
 6   Num_Creditos          510704 non-null  int64
 7   Ratio_Interes         510703 non-null  float64
 8   Duracion              510700 non-null  float64
 9   Ratio_Deuda_Ingresos  510702 non-null  float64
 10  Estudios              510701 non-null  object
 11  Tipo_Jornada_Laboral  510703 non-null  object
 12  Estado_Civil          510703 non-null  object
 13  Posesion_Hipoteca     510701 non-null  float64
 14  Personas_Cargo        510703 non-null  float64
 15  Proposito             510701 non-null  object
 16  Fiador                510701 non-null  float64
 17  Impago                510704 non-null  int64
 18  Prima                 510700 non-null  float64
dtypes: float64(9), int64(5), object(5)
memory usage: 74.0+ MB

In [9]:
Prestamos.describe()

,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Posesion_Hipoteca,Personas_Cargo,Fiador,Impago,Prima
count,510704.000000,510703.000000,510704.000000,510704.000000,510702.000000,510704.000000,510703.000000,510700.000000,510702.000000,510701.000000,510703.000000,510701.000000,510704.000000,510700.000000
mean,39.651274,41504.275875,45045.782232,692.147957,212.687775,2.000294,10.667369,37.222134,0.321258,0.350324,0.449567,0.299813,0.116128,385.290339
std,10.088274,16016.428381,46632.629842,87.658149,150.824970,1.000185,3.807198,14.170406,0.181096,0.477072,0.497450,0.458177,0.320379,267.454495
min,19.000000,16000.000000,3000.000000,398.000000,0.000000,1.000000,2.010000,12.000000,0.100000,0.000000,0.000000,0.000000,0.000000,10.000000
25%,33.000000,30481.000000,15033.000000,635.000000,69.000000,1.000000,7.960000,24.000000,0.140000,0.000000,0.000000,0.000000,0.000000,137.700000
50%,39.000000,39099.000000,40000.000000,704.000000,207.000000,2.000000,10.580000,36.000000,0.290000,0.000000,0.000000,0.000000,0.000000,336.860000
75%,46.000000,50083.000000,47326.000000,761.000000,337.000000,3.000000,13.250000,48.000000,0.550000,1.000000,1.000000,1.000000,0.000000,615.360000
max,64.000000,120000.000000,400000.000000,845.000000,639.000000,4.000000,24.440000,60.000000,0.550000,1.000000,1.000000,1.000000,1.000000,800.000000

In [16]:
#filtrar el proposito por educacion
Prestamos_educacion = Prestamos[Prestamos["Proposito"] == "Educación"]

In [17]:
Prestamos_educacion.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
4,KG9CT9,34,56572.0,73978,763,86.0,1,13.91,60.0,0.55,Máster,Tiempo parcial,Soltero,0.0,0.0,Educación,0.0,0,800.00
5,V5O0K9,37,68698.0,150000,824,162.0,2,10.53,24.0,0.37,Máster,Jornada completa,Casado,1.0,0.0,Educación,0.0,0,580.00
6,YE5GD0,40,50000.0,7490,671,167.0,2,9.24,60.0,0.10,Grado Universitario,Autónomo,Casado,1.0,1.0,Educación,0.0,0,130.00
11,Q6HQ3D,38,63033.0,11801,649,196.0,1,7.63,48.0,0.10,Grado Universitario,Tiempo parcial,Soltero,0.0,1.0,Educación,0.0,0,168.08
12,XO8CO4,19,22301.0,40000,788,17.0,4,8.40,36.0,0.50,Escolar,Jornada completa,Soltero,1.0,1.0,Educación,1.0,0,293.94

In [18]:
Prestamos_educacion.duplicated().sum()

np.int64(1)

In [19]:
#eliminar los duplicados de la base de datos Prestamos_educacion
Prestamos_educacion.drop_duplicates(inplace=True)

C:\Users\Oier\AppData\Local\Temp\ipykernel_21136\333429850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Prestamos_educacion.drop_duplicates(inplace=True)

In [20]:
Prestamos_educacion.isna().sum()

ID                      0
Edad                    0
Ingresos                0
Monto_Inicial           0
Scoring_Crediticio      0
Meses_Empleo            0
Num_Creditos            0
Ratio_Interes           1
Duracion                0
Ratio_Deuda_Ingresos    0
Estudios                1
Tipo_Jornada_Laboral    0
Estado_Civil            0
Posesion_Hipoteca       0
Personas_Cargo          0
Proposito               0
Fiador                  0
Impago                  0
Prima                   0
dtype: int64

In [21]:
Prestamos_educacion["Ratio_Interes"] = Prestamos_educacion["Ratio_Interes"].fillna(
    Prestamos_educacion["Ratio_Interes"].median())

C:\Users\Oier\AppData\Local\Temp\ipykernel_21136\1063342912.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Prestamos_educacion["Ratio_Interes"] = Prestamos_educacion["Ratio_Interes"].fillna(

In [22]:
Prestamos_educacion["Estudios"] = Prestamos_educacion["Estudios"].fillna(
    Prestamos_educacion["Estudios"].mode()[0])

C:\Users\Oier\AppData\Local\Temp\ipykernel_21136\1649855884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Prestamos_educacion["Estudios"] = Prestamos_educacion["Estudios"].fillna(

In [23]:
Prestamos_educacion.isna().sum()

ID                      0
Edad                    0
Ingresos                0
Monto_Inicial           0
Scoring_Crediticio      0
Meses_Empleo            0
Num_Creditos            0
Ratio_Interes           0
Duracion                0
Ratio_Deuda_Ingresos    0
Estudios                0
Tipo_Jornada_Laboral    0
Estado_Civil            0
Posesion_Hipoteca       0
Personas_Cargo          0
Proposito               0
Fiador                  0
Impago                  0
Prima                   0
dtype: int64